# Generated by Django 4.1.9 on 2023-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='movie_timing',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
