# Generated by Django 4.1.9 on 2023-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_seat_date_seat_movie_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movie_timing',
        ),
        migrations.AddField(
            model_name='theater',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theater',
            name='first_show',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theater',
            name='second_show',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theater',
            name='third_show',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='movie_timing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
