# Generated by Django 4.1.9 on 2023-08-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_theater_first_show_alter_theater_second_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IsAdminUser',
            field=models.BooleanField(default=False),
        ),
    ]
