# Generated by Django 4.1.9 on 2023-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.TextField(default=None, max_length=2200),
            preserve_default=False,
        ),
    ]
