# Generated by Django 4.1.9 on 2023-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_seat_number_bookingseat_seat_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_numbers',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
