# Generated by Django 4.1.9 on 2023-08-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_seat_seat_numbers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSeat',
        ),
    ]
