# Generated by Django 4.1.9 on 2023-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_seat_seat_numbers_bookingseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingSeat',
        ),
    ]
